site:
<<<<<<< HEAD
  title: OpenCPN Developer Manual
  url: https://leamas.github.io/ocpn-manuals/
  start_page:  ocpn-dev-manual:ROOT:intro-AboutThisManual.adoc

content:
  sources:
    - url: https://github.com/rgleason/ocpn-dev-manual
      branches: main
      edit_url: true
    - url: https://github.com/leamas/ocpn-pi-docs.git
      branches: main
      edit_url: false
    - url: https://github.com/Rasbats/managed_plugins.git
      branches: asciidoc
      edit_url: false
      start_path: manual
ui:   
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: docs
  clean: true

runtime:
  fetch: true

asciidoc:
  attributes:
    page-resource_1_title: OpenCPN.org
    page-resource_1_url: https://www.opencpn.org/
    page-resource_2_title: User Manual
    page-resource_2_url: |
      https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
    page-resource_3_title: Github Site
    page-resource_3_url: https://github.com/opencpn/OpenCPN
    page-resource_4_title: Bugtracker
    page-resource_4_url: https://opencpn.org/flyspray/
    page-resource_5_title: Plugin Manual (WIP)
    page-resource_5_url: https://rasbats.github.io/opencpn-plugins-manual/
=======
  title: OpenCPN Plugins Manual
  ### the 404 page and sitemap files only get generated when the url property is seto
  url: https://rasbats.github.io/ocpn-user-plugins-manual/
  start_page: ocpn-user-plugins-manual:ROOT:index.adoc

content:
  sources:
    - url: .
      branches: HEAD 
    #- url: https://github.com/Rasbats/ocpn-user-plugins-manual
      #branches: main      
      #edit_url: true
      
ui:   
  bundle:
    #url: https://github.com/Rasbats/ocpn-manuals-test/raw/main/ui-bundle.zip
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  
output:
  clean: true
  dir: ./docs


>>>>>>> c544684 (test)
