site:
  title: OpenCPN Plugins Manual
  # the 404 page and sitemap files only get generated when the url property is seto
  url: https://github.com/Rasbats/opencpn-plugins-manual
  start_page: opencpn-master-plugins::index.adoc
  
  
content:
  sources:   
    - url: https://github.com/Rasbats/opencpn-plugins-manual
      branches: main
      start_paths: 
      - manual
      - manual-beta
      
          
    - url: https://github.com/Rasbats/shipdriver_pi.git    
      branches: master
      start_path: manual/shipdriver
      edit_url: true 
      
    - url: https://github.com/Rasbats/otcurrent_pi.git    
      branches: master
      start_path: manual/otcurrent
      edit_url: true
      
    - url: https://github.com/Rasbats/photolayer_pi.git    
      branches: master
      start_path: manual/photolayer
      edit_url: true

    - url: https://github.com/Rasbats/DR_pi.git    
      branches: master
      start_path: manual/dead_reckoning
      edit_url: true
      
    - url: https://github.com/rgleason/watchdog_pi
      branches: master
      start_path: manual/watchdog
      edit_url: true
      
    - url: https://github.com/jongough/ocpn_draw_pi.git 
      branches: master
      start_path: manual/odraw
      edit_url: true
    
    - url: https://github.com/opencpn-radar-pi/radar_pi.git 
      branches: master
      start_path: manual/radar
      edit_url: true
    
    - url: https://github.com/rgleason/dashboard_tactics_pi.git
      branches: mnt151-frontend2
      start_path: manual/dash-t
      edit_url: true
    
    - url: https://github.com/Rasbats/vfkaps_pi.git    
      branches: master
      start_path: manual/vfkaps
      edit_url: true
    
    - url: https://github.com/Rasbats/sar_pi.git    
      branches: master
      start_path: manual/sar
      edit_url: true
    
    - url: https://github.com/nohal/aisradar_pi.git   
      branches: master
      start_path: manual/ais_radar_display
      edit_url: true

    - url: https://github.com/nohal/vdr_pi.git   
      branches: master
      start_path: manual/vdr
      edit_url: true

    - url: https://github.com/nohal/gecomapi_pi.git   
      branches: master
      start_path: manual/googleearth
      edit_url: true

    - url: https://github.com/nohal/iacfleet_pi.git   
      branches: master
      start_path: manual/iacfleet
      edit_url: true

    - url: https://github.com/nohal/launcher_pi.git   
      branches: master
      start_path: manual/launcher
      edit_url: true

    - url: https://github.com/nohal/ocpndebugger_pi.git   
      branches: master
      start_path: manual/debugger
      edit_url: true

    - url: https://github.com/nohal/objsearch_pi.git   
      branches: master
      start_path: manual/objsearch
      edit_url: true

ui:   
  bundle:
      url: ./ui-bundle.zip
      snapshot: true  

output:
  dir: ./docs
