site:
  title: Local Preview
  url: https://github.com/Rasbats/ocpn-user-plugins-manual
  start_page: ocpn-user-plugins::index.adoc

content:
  sources:  
    - url: https://github.com/Rasbats/ocpn-user-plugins
      branches: master
      start_path: manual
      edit_url: false

    - url:  https://github.com/Rasbats/shipdriver_pi.git
      branches: master
      edit_url: true
      start_path: manual

ui:
  bundle:
    url: https://github.com/Rasbats/ocpn-user-plugins-manual/raw/main/ui-bundle.zip?job=bundle-stable
    snapshot: true
  
