site:
  title: OpenCPN Users Plugins Manual
  url: http://mikerossiter.co.uk/site
  start_page: ocpn-users-plugins-manual::user_plugins_guide.adoc

content:
  sources:
    - url: https://github.com/Rasbats/ocpn-users-plugins.git
      branches: main
      edit_url: false
    - url:  https://github.com/Rasbats/shipdriver_pi.git
      branches: master
      edit_url: true
      start_path: manual

ui:
  bundle:
    url: https://github.com/Rasbats/opencpn_plugins_docs/raw/main/ui-bundle.zip
    snapshot: true
