site:
  title: Local Preview
  start_page: user-plugins-manual:nav.adoc

content:
  sources:  
    - url: .
      branches: HEAD
      
    - url: https://github.com/Rasbats/ocpn-user-plugins.git
      branches: main
      edit_url: false
      
    - url:  https://github.com/Rasbats/shipdriver_pi.git
      branches: master
      edit_url: true
      start_path: manual

ui:
  bundle:
    url: https://github.com/Rasbats/ocpn-user-plugins-manual/raw/main/ui-bundle.zip?job=bundle-stable
    snapshot: true
  default_layout: with_menu
output:
  clean: true
  dir: ./public
  destinations:
  - provider: archive
runtime:
  pull: true
  cache_dir: ./cache
