var dir_8907df15be1e56c6854f77d93ab99015 =
[
    [ "altitude.cpp", "altitude_8cpp.html", null ],
    [ "altitude.h", "altitude_8h.html", "altitude_8h" ],
    [ "baro_history.cpp", "baro__history_8cpp.html", null ],
    [ "baro_history.h", "baro__history_8h.html", "baro__history_8h" ],
    [ "clock.cpp", "clock_8cpp.html", null ],
    [ "clock.h", "clock_8h.html", "clock_8h" ],
    [ "compass.cpp", "plugins_2dashboard__pi_2src_2compass_8cpp.html", null ],
    [ "compass.h", "plugins_2dashboard__pi_2src_2compass_8h.html", "plugins_2dashboard__pi_2src_2compass_8h" ],
    [ "dashboard_pi.cpp", "dashboard__pi_8cpp.html", null ],
    [ "dashboard_pi.h", "dashboard__pi_8h.html", "dashboard__pi_8h" ],
    [ "depth.cpp", "depth_8cpp.html", null ],
    [ "depth.h", "depth_8h.html", "depth_8h" ],
    [ "dial.cpp", "dial_8cpp.html", null ],
    [ "dial.h", "dial_8h.html", "dial_8h" ],
    [ "from_ownship.cpp", "from__ownship_8cpp.html", null ],
    [ "from_ownship.h", "from__ownship_8h.html", "from__ownship_8h" ],
    [ "gps.cpp", "gps_8cpp.html", null ],
    [ "gps.h", "gps_8h.html", "gps_8h" ],
    [ "icons.cpp", "dashboard__pi_2src_2icons_8cpp_source.html", null ],
    [ "icons.h", "dashboard__pi_2src_2icons_8h_source.html", null ],
    [ "iir_filter.cpp", "iir__filter_8cpp_source.html", null ],
    [ "iir_filter.h", "iir__filter_8h.html", "iir__filter_8h" ],
    [ "instrument.cpp", "instrument_8cpp.html", null ],
    [ "instrument.h", "instrument_8h.html", "instrument_8h" ],
    [ "rudder_angle.cpp", "rudder__angle_8cpp.html", null ],
    [ "rudder_angle.h", "rudder__angle_8h.html", "rudder__angle_8h" ],
    [ "speedometer.cpp", "speedometer_8cpp.html", null ],
    [ "speedometer.h", "speedometer_8h.html", "speedometer_8h" ],
    [ "wind.cpp", "wind_8cpp.html", null ],
    [ "wind.h", "wind_8h.html", "wind_8h" ],
    [ "wind_history.cpp", "wind__history_8cpp.html", null ],
    [ "wind_history.h", "wind__history_8h.html", "wind__history_8h" ]
];