---
name: OpenCPN Development Manual

on:
  push:
    branches:
      - build
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Build and deploy"
        run: ci/build-and-deploy.sh
